### ISSUE TITLE
Question about code of Data Preprocessing

### ISSUE THREAD

**Issue by ZZX-11** [Icyrockton/FVA#1]
Hi！Thank you for your work, when I run the `getgraphs.py`  `gcn.subprocess_cmd(command, verbose=verbose)`, I encounter this problem:
![image](https://github.com/Icyrockton/FVA/assets/113749872/3238cc35-1c5f-410c-a79e-c4af6e9089b5)

After I delete `debug(output[1].decode()) `:
![image](https://github.com/Icyrockton/FVA/assets/113749872/a378ca7c-108f-4222-bd68-4b8e8b3da499)
I still can't get `edges.json` and `nodes.json`
can you help us with this or directly provide your graph datasets ?

**Comment by Icyrockton** [comment]
Hi, you need to run joern scripts on **Linux**, Windows is not supported.
